var GAME_LEVELS = [
  ["                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "                                                                ",
   "              q                                                 ",
   "          xxxxxxxxx                                             ",
   "                               xxxxxxxxx                        ",
   "xx                                          m      q            ",
   "xx                                        xxxxxxxxxx            ",
   "xx                    xxx                                       ",
   "xx                                                              ",
   "xx                                                              ",
   "xx   @                       m   q        xxxxx               q ",
   "xxxxxxxxxxx            xxxxxxxxxxxxxx                xxxxxxxxxxx",
   "xxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxx                xxxxxxxxxxx",
   "xxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxx                xxxxxxxxxxx",
   "xxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxx                xxxxxxxxxxx",
   "xxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxx                xxxxxxxxxxx",
   "xxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxx                xxxxxxxxxxx",
   "xxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxx                xxxxxxxxxxx"],

  ["yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
   "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy                                   yy",
   "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy                                   yy",
   "                                                                                                                  ",
   "                                                q                                                 r               ",
   "                                           yyyyyyyyyyy                                                        q   ",
   "                                                                                           yyyyyyyyyyyyyyyyyyyyyyy",
   "                                                                                           yyyyyyyyyyyyyyyyyyyyyyy",
   "                        q           m                                                      yyyyyyyyyyyyyyyyyyyyyyy",
   "y                     yyyyy     yyyyyyyyyy                                         yyy                            ",
   "y                     yyyyy                                                        yyy                            ",
   "y             q       yyyyy                                                        yyy                            ",
   "y           yyyyy     yyyyy                              yyyyyyyyyy          q     yyy                            ",
   "y           yyyyy     yyyyy                                                 yyy    yyy                            ",
   "y   @       yyyyy     yyyyy                                                 yyy    yyy                            ",
   "yyyyyyy     yyyyy     yyyyy                                           yyy   yyy    yyy                            ",
   "yyyyyyyyyyyyyyyyyyyyyyyyyyy                                           yyy   yyy    yyy                            ",
   "yyyyyyyyyyyyyyyyyyyyyyyyyyy                                           yyyvvvyyyvvvvyyy                            ",
   "yyyyyyyyyyyyyyyyyyyyyyyyyyyvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvyyyyyyyyyyyyyyyyvvvvvvvvvvvvvvvvvvvvvvvvvvvv"],
   
  ["                                                                                                                  ",  
   "                                                                                                                  ",
   "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
   "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
   "                                                    uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
   "         q                                    q    uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
   "uuuuuuuuuuuuuuuuuuuuu                    uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
   "uuuuuuuuuuuuuuuuuuuuuuu              uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
   "uuuuuuuuuuuuuuuuuuuuuuuuuu                                                                                        ",
   "uuuuuuuuuuuuuuuuuuuuuuuuuuuu                                                                                      ",
   "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuu                            q                                                       ",
   "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuvuvuuvvuvuuuuuuuuuuuuuuuuuuuu       m                                    ",
   "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu                              ",
   "                                                                                                                  ",
   "                                                                                        uuuuuu                    ",
   "                                                                                         uuuu                     ",
   "                                                                                                     q            ",
   "                               q                                                                  uuuuuuu         ",
   "                          uuuuuuuuuuuu     uuuuu                         m                         uuuuu          ",
   "    @                       uuuuuuuu       uuuuu       q         uuuu  uuuuu  uuuu                          uuuu  ",
   "uuuuuuuuuuuuuu                 uu          uuuuu     uuuuu       uuuu  uuuuu  uuuu                           uu   ",
   "uuuuuuuuuuuuuuu                            uuuuu     uuuuu       uuuu  uuuuu  uuuu                  uuuuuuu       ",
   "uuuuuuuuuuuuuuuuuuuuuu                     uuuuu     uuuuu       uuuu  uuuuu  uuuu                                ",
   "uuuuuuuuuuuuuuuuuuuuuu                     uuuuu     uuuuu       uuuu  uuuuu  uuuu           m                q   ",
   "uuuuuuuuuuuuuuuuuuuuuu                     uuuuu     uuuuu       uuuu  uuuuu  uuuu  uuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
   "uuuuuuuuuuuuuuuuuuuuuuu       m            uuuuu     uuuuu       uuuu  uuuuu  uuuu  uuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
   "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu    uuuuu     uuuuu       uuuu  uuuuu  uuuu  uuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
   "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu    uuuuu     uuuuu       uuuu  uuuuu  uuuu uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
   "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu    uuuuu     uuuuu       uuuu  uuuuu  uuuu uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
   "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu    uuuuu     uuuuu       uuuu  uuuuu  uuuu  uuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
   "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu   uuuuu     uuuuu       uuuu  uuuuu  uuuu  uuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
   "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu   uuuuu     uuuuu       uuuu  uuuuu  uuuu  uuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
   "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu uuuuu     uuuuu       uuuu  uuuuu  uuuu    uuuuuuuuuuuuuuuuuuuuuuuuuuuu",
   "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu uuuuu     uuuuu       uuuu  uuuuu  uuuu   uuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
   "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu uuuuu     uuuuu       uuuu  uuuuu  uuuu   uuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
   "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu     uuuuu       uuuu  uuuuu  uuuu  uuuuuuuuuuuuuuuuuuuuuuuuuuuuuu"],
  
  

  ["wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
   "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
   "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
   "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww                                               ",
   "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww                                                 ",
   "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww                                                ",
   "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww                                     m     q     ",
   "wwwwwwwwwwwwwwwwwww                   wwwwwwwwwwwwwwwwwwwwww                                    wwwwwwwwwwwwww",
   "wwwwwwwwwwwwwwwwwww                               wwwwwwwww                                 wwwwwwwwwwwwwwwwww",
   "ww                                                                                          wwwwwwwwwwwwwwwwww",
   "ww                                                                                wwwww     wwwwwwwwwwwwwwwwww",
   "ww                        m           q                                                                       ",
   "ww@          q    www   wwwwwwww     wwww                                                                    ",
   "wwwwwwwwwwwwwwwwwww                    ww           q                                                         ",
   "wwwwwwwwwwwwwwwwwwvvvvvvvvvvvvvvvvvvvvvww                                    w                                ",
   "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww      wwwwwwwwwwwww                                                  ",
   "                                       ww     www  m                                  q                       ",
   "                                       ww     www  m                                wwwwww                    ",
   "                                       ww      ww        wwwwwwwwwwwwwww                                      ",
   "                                       ww      ww       ww             w                      wwwwwwwwww      ",
   "                                       ww      wwm q  mwww             w  m                                   ",
   "                                       ww      wwwwwwwwwww             wwwwwww                                ",
   "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww                                                                     ",
   "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww                                         wwwwwwwwww                  ",
   "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww                     q                                               ",
   "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww                                                                     ",
   "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww      wwwwwwwwwwww                                ",
   "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww      wwwwwwwwwwww                                ",
   "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww     wwwwwwwwwwwwww                              ",
   "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww      wwwwwwwwwwwwww                              "],


 ];

  

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
